# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: abd6447461b1ba1f99f25812360ad5923d336baf89a483bd1309ac3883d32578390236a6024a8c84e2a07496c37128ee0299a504c126dd6bbe05e7fd84c14601

test:
  secret_key_base: 76ad06928092a689762fc8b4459260f1042b2bf692f453227b8991a5aa72601fde1b4789d52dae497c6fd587deec3a77d1a2e082d62d2991126a2656d1474ba1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
